# 指定语言环境
language: node_js
# 指定需要sudo权限
sudo: required
# 指定node_js版本
node_js: 
  - 8.1.3
# 指定缓存模块，可选。缓存可加快编译速度。
cache:
  directories:
    - node_modules

# 指定博客源码分支，因人而异。hexo博客源码托管在独立repo则不用设置此项
branches:
  only:
    - hexo 

before_install:
  - npm install -g hexo-cli

# Start: Build Lifecycle
install:
  - yarn install

# 执行清缓存，生成网页操作
script:
  - hexo clean
  - hexo generate

# 设置git提交名，邮箱；替换真实token到_config.yml文件，最后depoy部署

# after_script:
#   - git config user.name "heliuphy"
#   - git config user.email "liuhephy@gmail.com"
#   # 替换同目录下的_config.yml文件中gh_token字符串为travis后台刚才配置的变量，注意此处sed命令用了双引号。单引号无效！
#   - sed -i "s/gh_token/${GH_TOKEN}/g" ./_config.yml
#   - hexo deploy
# # End: Build LifeCycle

after_script:
  - cd ./public
  - git init
  - git config user.name "heliuphy"
  - git config user.email "liuhephy@gmail.com"
  - git add .
  - git commit -m "TravisCI 自动部署"
  # Github Pages
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
  # Coding Pages
  - git push --force --quiet "https://heliu:${CO_TOKEN}@${CO_REF}" master:master

env:
 global:
   # Github Pages
   - GH_REF: github.com/heliuphy/heliuphy.github.io
   # Coding Pages
   - CO_REF: git.dev.tencent.com/heliu/hexo.git
   